#!/usr/bin/env bash
# Create user if it doesn't exist
if ! getent passwd appraisers >/dev/null; then
    echo "Creating Appraiser Service user account"
    adduser --quiet --system --group --home /var/run/appraisers appraisers
fi
# Stop the service if it's already running
if systemctl is-active appraisers.service >/dev/null; then
    echo "Stopping the Appraiser Service"
    systemctl stop appraisers.service
fi
