#!/usr/bin/env bash
# Stop the service if it's already running
if systemctl is-active appraisers.service >/dev/null; then
    echo "Stopping the Appraiser Service"
    systemctl stop appraisers.service
fi
